### PR TITLE
JSON Related errors are resolved and json files are compatible to json in python

### PR DESCRIPTION
**Pull request by ashutosh1919**
Rather than having json objects in each line of the file which can not be read entirely as json object, I have converted whole file as a json object which can be read by **json.loads(file_data)** Also each resume records can be accessed as an array.

I have personally faced the issue because some editors are not supporting the very long string to be read in one line so incomplete string was giving error in train.py.

But now, code works fine and model works fine. I have tested it well.

Json train and test data files are converted using **stack algorithm of brackets**. 
Also, it is my humble suggestion that please integrate this project with travis or circle ci so that the contributors don't need to thoroughly check the tests and you can easily merge changes.

Thank you for the project!
@abhishek-narayanan-dataturks, Please review this PR as soon as possible since many of the users might have faced the same error.

### CODE REVIEW

**Comment by skanda44** [comment]
provide the complete project after solving the json issue

**Comment by ashutosh1919** [comment]
> provide the complete project after solving the json issue

@skanda44, You can check the master branch of my forked project [here](https://github.com/ashutosh1919/Entity-Recognition-In-Resumes-SpaCy). It is completely working and I have tested it. The **spacy version used was 2.0.16 and msgpack version 0.5.6**. Please look at it and run the file train.py to check whether it is working correctly or not.

**Comment by supreetha23** [comment]
hi ashutosh, 

C:\Users\Supreetha D\Desktop\codefinal\Entity-Recognition-In-Resumes-SpaCy>python train.py
ERROR:root:Unable to process /traindata.json
error = 'charmap' codec can't decode byte 0x9d in position 11125: character maps to <undefined>
Traceback (most recent call last):
  File "train.py", line 21, in convert_dataturks_to_spacy
    lines = f.read()
  File "C:\Users\Supreetha D\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 11125: character maps to <undefined>
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    train_spacy()
  File "train.py", line 61, in train_spacy
    for _, annotations in TRAIN_DATA:
TypeError: 'NoneType' object is not iterable

please help in solving this error. I installed msgpack and spacy

**Comment by ashutosh1919** [comment]
> hi ashutosh,
> 
> C:\Users\Supreetha D\Desktop\codefinal\Entity-Recognition-In-Resumes-SpaCy>python train.py
> ERROR:root:Unable to process /traindata.json
> error = 'charmap' codec can't decode byte 0x9d in position 11125: character maps to 
> Traceback (most recent call last):
> File "train.py", line 21, in convert_dataturks_to_spacy
> lines = f.read()
> File "C:\Users\Supreetha D\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
> return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 11125: character maps to 
> Traceback (most recent call last):
> File "train.py", line 131, in 
> train_spacy()
> File "train.py", line 61, in train_spacy
> for _, annotations in TRAIN_DATA:
> TypeError: 'NoneType' object is not iterable
> 
> please help in solving this error. I installed msgpack and spacy

@supreetha23 , Let me integrate my project with travis where I will build virtualenv with proper spacy and msgpack versions and will run the project here on github so that you can easily spot the difference and the working code. **Note that spacy is very sensitive library and its current versions are very very vulnerable and GoldParse, which is used in this project is erroneous in latest version of spacy**. So, let me integrate travis and will get back to you as soon as possible. 

Thanks for the quick response @supreetha23 ,@skanda44.

**Comment by OmkarPathak** [comment]
@supreetha23 had the same problem. I just replaced the line `with open(dataturks_JSON_FilePath, 'r') as f:` with this: `with open(dataturks_JSON_FilePath, 'r', encoding="utf8") as f:` in the `convert_dataturks_to_spacy` function.

Also refer PR #15 to add the function` trim_entity_spans()`

**Comment by ashutosh1919** [comment]
> @supreetha23 had the same problem. I just replaced the line `with iopen(dataturks_JSON_FilePath, 'r') as f:` with this: `with open(dataturks_JSON_FilePath, 'r', encoding="utf8") as f:` in the `convert_dataturks_to_spacy` function

Yes, I got that. The problem is not just that one. The problem is also in train and test data files. they are not really json files. They are just combined json objects written in each line. I have corrected that data files in [my forked repo](https://github.com/ashutosh1919/Entity-Recognition-In-Resumes-SpaCy). I am currently working on making dockerfile and containers so that the implementation doesn't depend on type of OS. Also, the spacy versions have many conflicts in newer versions. So, it may be possible that newer spacy versions in windows will give error. Also, the default virtualenv encoding in some windows laptops is 'cp437' and not 'utf-8'. So, there is also a big proble. The one simple solution to all these problem is to create docker (linux OS) so that it will serve the functionality.

**Comment by OmkarPathak** [comment]
@ashutosh1919 thanks a lot for your efforts. Until you are done with your development, the above simple solution works! 😄

**Pull request closed without merging**
